# Generated by Django 5.2.16 on 2026-08-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='created_at',
            new_name='create',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='updated_at',
            new_name='update',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='comments_require_approval',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='posts_per_page',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='registration_enabled',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='comments_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_seo_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(max_length=100),
        ),
    ]
