# Generated by Django 5.2.16 on 2026-08-12 09:56

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_created_at_sitesettings_create_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="default_seo_description",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="site_description",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
