# Generated by Django 5.2.16 on 2026-08-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sitesettings_default_seo_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='posts_per_page',
            field=models.PositiveIntegerField(default=9),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='registration_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
