# Generated by Django 5.2.16 on 2026-08-10 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='blogpostdailystat',
            name='unique_post_daily_stat',
        ),
        migrations.RemoveField(
            model_name='blogpostdailystat',
            name='unique_views',
        ),
        migrations.AlterField(
            model_name='blogpostdailystat',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost'),
        ),
    ]
