# Generated by Django 5.2.16 on 2026-08-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_remove_blogpostdailystat_unique_post_daily_stat_and_more'),
        ('blog', '0003_alter_blogpost_content'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='blogpostdailystat',
            constraint=models.UniqueConstraint(fields=('post', 'stat_date'), name='unique_post_daily_stat'),
        ),
    ]
