# Generated by Django 5.2.16 on 2026-08-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='created_at',
            new_name='create',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='updated_at',
            new_name='update',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
