# Generated by Django 5.2.16 on 2026-08-12 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="scheduled_for",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="posts",
                to="blog.blogcategory",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="published_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                blank=True,
                editable=False,
                max_length=270,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_review", "Pending Review"),
                    ("approved", "Approved"),
                    ("scheduled", "Scheduled"),
                    ("published", "Published"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="summary",
            field=models.CharField(max_length=500),
        ),
    ]
