# Generated by Django 5.2.16 on 2026-08-12 07:47

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogpost_scheduled_for_alter_blogpost_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
