# Generated by Django 5.2.16 on 2026-08-15 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blogpost_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogcategory",
            options={"ordering": ["sort_order", "name"]},
        ),
        migrations.AlterModelOptions(
            name="blogpost",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="blogcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="blog.blogcategory",
            ),
        ),
        migrations.AddField(
            model_name="blogcategory",
            name="seo_description",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="blogcategory",
            name="seo_title",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="blogcategory",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="reading_time",
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("only_members", "Only Members"),
                    ("private", "Private"),
                ],
                default="public",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_review", "Pending Review"),
                    ("approved", "Approved"),
                    ("scheduled", "Scheduled"),
                    ("published", "Published"),
                    ("rejected", "Rejected"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
    ]
