# Generated by Django 5.2.16 on 2026-08-15 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSlugRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_slug', models.SlugField(allow_unicode=True, max_length=270, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slug_redirects', to='blog.blogpost')),
            ],
        ),
    ]
