# Generated by Django 5.2.16 on 2026-08-15 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_allow_comments_blogpost_bookmark_count_and_more'),
        ('blog', '0004_blogslugredirect'),
    ]

    operations = [
    ]
