# Generated by Django 5.2.16 on 2026-08-15 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_blogcategory_options_alter_blogpost_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="reading_time",
        ),
    ]
