# Generated by Django 5.2.16 on 2026-08-15 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_merge_20260815_1723"),
        ("blog", "0005_remove_blogpost_reading_time"),
    ]

    operations = []
