# Generated by Django 5.2.16 on 2026-08-15 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlogAuthorFollow",
        ),
    ]