# Generated by Django 5.2.16 on 2026-08-15 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_allow_comments_blogpost_bookmark_count_and_more'),
        ('social', '0002_remove_blogauthorfollow_author_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogbookmark',
            options={},
        ),
        migrations.AlterModelOptions(
            name='blogcontentreport',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='blogbookmark',
            name='unique_bookmark_per_post_user',
        ),
        migrations.RemoveConstraint(
            model_name='blogcontentreport',
            name='report_exactly_one_target',
        ),
        migrations.RemoveConstraint(
            model_name='blogcontentreport',
            name='unique_reporter_post',
        ),
        migrations.RemoveConstraint(
            model_name='blogcontentreport',
            name='unique_reporter_comment',
        ),
        migrations.RemoveConstraint(
            model_name='blogreaction',
            name='unique_reaction_per_post_user',
        ),
        migrations.AlterField(
            model_name='blogbookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogcontentreport',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='social.blogcomment'),
        ),
        migrations.AlterField(
            model_name='blogcontentreport',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='blog.blogpost'),
        ),
        migrations.AlterField(
            model_name='blogcontentreport',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('hate', 'Hate Speech'), ('copyright', 'Copyright'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='blogcontentreport',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogcontentreport',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogcontentreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogcontentreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='blogreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='blogbookmark',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_post_bookmark'),
        ),
        migrations.AddConstraint(
            model_name='blogcontentreport',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('comment__isnull', True), ('post__isnull', False)), models.Q(('comment__isnull', False), ('post__isnull', True)), _connector='OR'), name='one_report_target'),
        ),
        migrations.AddConstraint(
            model_name='blogreaction',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_post_reaction'),
        ),
    ]
