# Generated by Django 5.2.16 on 2026-08-09 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/')),
                ('original_name', models.CharField(editable=False, max_length=255)),
                ('mime_type', models.CharField(blank=True, editable=False, max_length=150)),
                ('file_size', models.PositiveBigIntegerField(default=0, editable=False)),
                ('width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, editable=False, help_text='Duration in seconds', null=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('caption', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('pdf', 'PDF'), ('other', 'Other')], max_length=20)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('cover', 'Cover'), ('content', 'Content'), ('gallery', 'Gallery')], max_length=20)),
                ('caption', models.TextField(blank=True)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='blog.blogpost')),
                ('media_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_placements', to='media.mediaasset')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('post', 'media_asset', 'purpose'), name='unique_post_media_purpose'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('purpose', 'cover')), fields=('post',), name='unique_active_cover_per_post')],
            },
        ),
    ]
